backend:
  name: git-gateway
  branch: main

media_folder: "src/img"
public_folder: "/img"

collections:
  - name: "images" 
    label: "Images"
    folder: "src/img"
    create: true 
    slug: "{{filename}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}
